name: Build and Release App

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build APKs
      run: ./gradlew -p ./app :app:assembleRelease
      env:
        GPR_TOKEN_READ: ${{ secrets.GPR_TOKEN_READ }}

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{runner.workspace}}/ramses-sample-app/app/build/outputs/apk/release/app-release.apk
